### ISSUE TITLE
[Question] I am curious which ColBERT model does this project use for generating multi-vectors?

### ISSUE THREAD

**Issue by yangzq50** [CosimoRulli/emvb#1]
Does JMPQ need a customized BERT model to function currectly?
And, in which case do you use OPQ instead of JMPQ?
Also, I noticed that the README file says "We will provide soon the scripts to build and convert indexes on a custom collection". Is this plan still valid?

**Comment by CosimoRulli** [comment]
Hey, 

Thank you for your interest.

- We use ColbertV2, with the embeddings generated using the original repository: https://github.com/stanford-futuredata/ColBERT.
- I don't think JMPQ requires a special BERT model. We use it by simply passing the model trained from the ColBERT repo. You may need to modify some helper functions, as JMPQ was originally meant to be used with ColBERTv1, I believe.
- The advantage of OPQ over JMPQ is that it does not require training queries, making it perfect for out-of-domain scenarios.
- I will try to update the scripts by the end of next week.

**Comment by CosimoRulli** [comment]
I am closing the issue, feel free to re-open it if you have any questions!
